version: '3.5'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  vaultunseal:
    build:
      context: .
      dockerfile: Dockerfile
    image: vaultunseal
    working_dir: /usr/src/app
    volumes:
      - ./config:/usr/src/app/config
    environment:
      - APP_NAME=vaultunseal
    # Overrides default command so things don't shut down after the process ends.
    command: sh -c 'python3.8 -m vaultunseal'
    restart: always

